# Generated by Django 5.2.5 on 2025-10-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_group_created_by_chat_group_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_group',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='chat_group',
            name='members',
        ),
    ]
