# Generated by Django 5.2.5 on 2025-10-16 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('chat', '0003_remove_chat_group_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_member', to='chat.chat_group'),
        ),
    ]
